### DISCUSSION TITLE
lv5048

### DISCUSSION THREAD

**Discussion by magnetus26** [syssi/esphome-pipsolar#11] [General]
hi Sebastian,
I put the bms project in pause.
now i will like to integrate my mppsolar lv5048 to my HA. I see that there is an esphome integration (PipSolar PV Inverter) and also your repository esphome-pipsolar.
do you know if any of them works with my inverter?
i have a step down and a rs232 to ttl converter already an of course an esp32
this is my ttl converter. according to the sapecs should be 3.3 tolerant.

![32736E53-9B0C-4A8B-9AA4-03A2BF0DDFB5](https://user-images.githubusercontent.com/22038983/159977968-f9a09eb7-8987-411f-964d-172286e351c1.jpeg)

73 de KP4MI
Miguel

**Comment by syssi** [comment]
You are on a good track. If your inverter is able to answer to QPIGS requests the pipsolar component should work for you. Just assemble all parts and give it a try. Please report your progress here.

**Comment by magnetus26** [comment]
im about to start.
im looking at the pipsolar integration but this is confusing and ugly (lol)

grid_rating_voltage:
      id: inverter0_grid_rating_voltage
      name: inverter0_grid_rating_voltage

can I change the id:, and the name:  for something that makes more sense to me?

does the name has to have the undescore ( _  ) or can i change them for spaces?

sorry for the silly questions I dont know how to code and i dont know yaml.

how is that you just use name and not id in your code?

grid_voltage:
      name: "${name} grid_voltage"

73 de KP4MI
Miguel

**Reply by syssi** [reply]
Feel free to change the `name` and the `id` value. The key (f.e. `grid_rating_voltage`) is important and cannot be customized. If you use spaces the entity id will be underscored. Just give it a try!

The `id` is important if you want to reference / control the entity from another line of code. It's hard to explain but you will understand the difference/need as soon you are a bit more familiar with ESPHome. As long you don't need IDs just skip it (don't provide IDs).

**Reply by syssi** [reply]
The documentation of ESPHome IDs: https://esphome.io/guides/configuration-types.html#config-id

**Comment by magnetus26** [comment]
OK Good News!!!
it works.
I use the esphome PipSolar PV Inverter integration attached are a picture of my circuit and the yaml file that I created
I used the 12V from pin 4 of the RJ45 connector. I didn't have any output at pin 7
so:
pin 1 TX 
pin 2 RX
pin 4 12V
pin 8 GND
[mppsolar-inverter-0.txt](https://github.com/syssi/esphome-pipsolar/files/8356039/mppsolar-inverter-0.txt)
![ac8cbf36-aaaf-4955-9269-3010196af8e8](https://user-images.githubusercontent.com/22038983/160251107-33229aee-1bfa-4c69-a290-bc2a0f7bdb43.JPG)
![Capture](https://user-images.githubusercontent.com/22038983/160251264-5a2e0844-c13a-4fee-8a69-43ad6ddb009e.PNG)

thanks for your help!!!

73 de KP4MI 
Miguel

**Reply by valeriotaccardo** [reply]
Hi! Good job!! Can you say me How you have integrated energy battery charge/discharge information? Pipsolar inverter don't have this information. There are only charge/discharge currente. Does You have calculate power and energy from (voltage * amper)?

**Reply by CrAzYDr1veR** [reply]
same problem but i'm on 8266 i don't understand how to make the pipsolar show up on the energy distribution flow card, shelly utility appears just fine.

EDIT: I am too stupid to be making this kid of stuff. All of this should be integrated or explicit on pipsolar.
magnetus26 file has the answer but still it's not working as it should because you need the pv input separated from charging the battery or running the house. Also no separated entities for charging or discharging the battery. He is doing a lot more than he tells...

    pv_charging_power:
      id: inverter0_pv_charging_power
      name : "PV Charging Power"
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 3
     
#
![energy flow card](https://github.com/syssi/esphome-pipsolar/assets/47764335/c6017562-4b5a-4ab9-a16e-b509b8913500)

**Comment by syssi** [comment]
Good job!

**Comment by magnetus26** [comment]
Hi Sebastian,
I'm thinking of switching from esphome native PipSolar PV Inverter device integration over yours, esphome-pip solar.
I have a few questions and requests:

1. will my LV5048 split phase inverter works with your repository? (I'm willing to test and report)

2. do I need to setup an MQTT broker?

3. will it be possible to add more switches, specifically Charger Source Priority: To configure the priority of charge source. In my Inverter is menu option 16 , and options are:

a. CSO - solar energy will charge battery as first priority. Utility will charge battery only when solar energy is not available.

b. CUt - Utility charge battery as first priority. Solar will charge battery only when utility power  is not available.

c. SNU - Solar energy and utility will charge battery at the same time.

d. OSO - Solar energy will be the only charger source no matter utility is available or not.

thanks
Miguel

**Comment by syssi** [comment]
1. Please stick to the official component as long as possible. This repository/project is just a support channel and sandbox to test new features / get a better understanding of the different device/protocol flavors. Could you provide a QPIGS response of your receiver and the number of PV strings / MPPTs of your device?
2. No. If you use Home Assistant just remove the `mqtt` section und use the native `api` instead. You should prefer the native api whenever possible it's more lightweight and speedy.
3. The SBU feature should work and will work at the official component in future as soon the fixed CRC check is merged: https://github.com/esphome/esphome/pull/3316 Without this fix the inverter doesn't accept some commands because of an invalid checksum.

Andreas (the author of the official component) is working on a select entity which can be tested at the "pip8084" branch already using:

``` 
external_components:
  - source: github://syssi/esphome-pipsolar@pip8048
    refresh: 0s

select:
  - platform: pipsolar
    pipsolar_id: inverter0
    output_source_priority:
      id: inverter0_output_source_priority_select
      name: inverter0_output_source_priority_select
      optionsmap:
        "Utility first": "POP00"
        "Solar only": "POP01"
        "Solar Battery Utility": "POP02"
      statusmap:
        "0": "Utility first"
        "1": "Solar only"
        "2": "Solar Battery Utility"
```

Just give it a try!

**Comment by magnetus26** [comment]
I'm using 4 PV strings in parallel so just one string is going to the inverter and I only have one inverter.

here are some logs, let me know if the QPIGS response is there, if not please let me know how to add them:
[logs_mppsolar-inverter-0_logs.txt](https://github.com/syssi/esphome-pipsolar/files/8680075/logs_mppsolar-inverter-0_logs.txt)

the SBU feature is working, I can select the Output Source Priority:

`switch:
  - platform: pipsolar
    pipsolar_id: inverter0
    output_source_priority_utility:
      name: "Output Priority Utility"
    output_source_priority_solar:
      name: "Output Priority Solar"
    output_source_priority_battery:
      name: "Output Priority Battery"`

I will like to add the  Charger Source Priority.
that option (mentioned above) is not available either in the official component or your repository.

the Output Source Priority: (option1 in my inverter menu) will allow me to configure the load power source priority, basically which source will be used as output to power my house

the Charger Source Priority: (option16 in my inverter menu) will allow me to configure the the priority of charge source , basically which source will be used as charger for my battery bank.

attached is the inverter manual:
http://www.mppsolar.com/manual/SPLIT%20PHASE%20LV/LV5048%20split%20phase%20manual-20191024.pdf

**Reply by syssi** [reply]
Did you see this output?

https://esphome.io/components/pipsolar.html#output

| charger_source_priority (Optional): charger source priority;
| possible_values (Optional, list): a list of possible values default: 0,1,2,3

**Comment by magnetus26** [comment]
yes I saw the option, one as a sensor which I do have in my code and the same as an output, but don't know how to use the output one
and it wont be a switch so I can select the charge source I guess so I wont be able to select any option. am I correct? btw how to I use that output statement
 will it be something like this:
output:
  - platform: pipsolar
    pipsolar_id: inverter0
    charger_source_priority:
      id: inverter0_charger_source_priority_select

but then how I add the possible_values (Optional, list): a list of possible values default: 0,1,2,3?

thanks,
Miguel

**Reply by syssi** [reply]
The output is something like a internal switch. You have to add the `output:` section you mentioned to your config. Afterwards you can use the output ID at automations (at your config yaml).

**Comment by magnetus26** [comment]
added these lined to my yaml but I don't see any changes 

output:
  - platform: pipsolar
    pipsolar_id: inverter0
    battery_recharge_voltage:
      id: inverter0_battery_recharge_voltage_out
    charger_source_priority:
      id: inverter0_charger_source_priority_select

**Reply by syssi** [reply]
Outputs aren't exposed as Home Assistant entities. The are internal available and can be controlled by automations. You could try to use a select template to expose the output.

**Comment by magnetus26** [comment]
idk man, been trying for 2 hours and for the life of me cant make it work.
also if I switch from output_source_priority_battery to either output_source_priority_solar or output_source_priority_utility I wont be able to go back to battery. I can switch back and forth between utility and solar but it will not go to battery, that's true in both your repository and the official integration

idk if you can see that in the logs
[logs_mppsolar-inverter-0_logs.txt](https://github.com/syssi/esphome-pipsolar/files/8681765/logs_mppsolar-inverter-0_logs.txt)

**Reply by syssi** [reply]
I can see at the log you are using the official component with the broken CRC implementation. Please use the merge request mentioned above or this custom component and give it another try.

**Reply by magnetus26** [reply]
I tried the code listed above and seems to be working had to run and didnt have time to test had to take go and take care of mom will try tomorrow if it sunny today was a stinky day and will report and send some logs
thanks for all your help
do you accept donations? im in a budget but can spare a few dollars. you have been so helpful and patient I appreciate it
73
de KP4MI
Miguel

**Reply by syssi** [reply]
You are welcome! There is a "donate a coffee" button at the README page. I like to help and will continue to do so even without coffee. ;-) 73 de DO2KSM

**Comment by magnetus26** [comment]
I tried the new code and woks as expected it chcles between all 3 modes solar only, utility only and sbu, thanks so much

now when i switch to utility only (even if I do it manually) and the back to solar or sbu my inverter output stays in utility ( even if I go to the menu and verify that the mode has changed) I think thats a limitation of the inverter I did all these test with my battery at 100% soc and plenty of sun.
I also made sure that option 13 ( voltage point back to battery was set to a voltage that meets that requirement.

in another note I have a crazy idea and dont know if it possible:
either use de db9 port and an 8266 as serial to wifi to use with native watchpower android app ( dont know if i can have both connected rj45 amd db9) or add some code to my esp32 to be use as serial to wifi while using with esphome-pipsolar repository
anyways I dont know how to write the yaml code for either

thanks for all your support
73 de KP4MI
Miguel

**Reply by syssi** [reply]
You are talking about the SUB-D 9pol jack of your converter module, right? Your inverter provides only one serial interface via RJ45?

**Comment by magnetus26** [comment]
my inverter has both ports sub d9 and rj45 the both are serial ports but dont know if is 1 port 2 form factors or 2 separate serial ports
im using the rj45 with an esp32 as you can see in the picture a few posts above

**Reply by syssi** [reply]
Hmm.. interesting. I wasn't aware of a second connector. Are you sure the Watchpower Android App is able to handle a serial connection via WiFi? If I read this page it looks like some cloud is involved and the Dongle does some conversion here:

https://www.mppsolar.com/v3/portfolio/watchpower-wifi-new/

If the Android app is able to connect to a serial over wifi stream it's pretty easy to add a serial-to-network streamserver to the YAML. I did the same already for a ZigBee Gateway (the ZigBee Modem is attached to a serial port of an ESP): https://github.com/syssi/esphome-zb-gw03/blob/main/packages/core.yaml

**Comment by magnetus26** [comment]
yea you are correct  dongle does some conversion and goes to the cloud.
shoot im not home now i know for a fact that it has an rj45 the one that im using and a usb port i think that the sub d 9 is the wifi module it has a cable rj45 to sub d 9 ( btw i dont have that module )

have you seen that behavior, that the inverter output will still utility even if solar only or sbu are selected?
I see this if i change to utility and back to solar

![84C618C7-A76F-484F-BE26-1B302C5D1C7D](https://user-images.githubusercontent.com/22038983/168447821-cc9c7190-9541-44e1-8a44-98c9a708fa20.jpeg)

isntead of this

![868F28AB-6013-43F4-B3F1-D7CC489B9373](https://user-images.githubusercontent.com/22038983/168447882-e4d0ab63-8379-4b27-a0b7-70a39699856f.jpeg)

like i mentioned that happends with or without the esp32 module even if i change it using the menu

**Reply by jowser7** [reply]
I know that if you have the switch off, AC will go into bypass mode. You can change setting bypass enable/disable modes on option 23 on mine. Look for byE is probably on.   I'm using a smart switch on my AC input to remotely turn it on if I notice battery Ah are getting less than about 15%.  Eventually I want to automate changing option 16 after reading my shunt Ah left and if needed, enable the bypass.  I don't want the AC charging batteries too much if it gets low, only charge enough to make it to morning.  But then I also run down to shut the switch off because even in eco mode, it drains the battery. That's another thing I want to do, such as put a relay to the inverter switch. But I'm not confident if esp32 keeps the latch state.  hope this helps you.
![image](https://user-images.githubusercontent.com/45370282/169937833-ce7ce4f8-3a5d-45e2-bf84-8eff15f3d92a.png)

**Comment by magnetus26** [comment]
hello Sebastian,
do you think its possible to add a sensor to my slit phase inverter to monitor both sides ?

I will like to be able to monitor
grid voltage phase A
grid voltage phase B
grid current phase A
grid current phase B
ac output voltage phase A
ac output voltage phase B

thank you

73 de KP4MI 
Miguel

**Reply by syssi** [reply]
Could you create an issue here and could you try to provide some protocol details? https://github.com/syssi/esphome-pipsolar/issues

**Comment by magnetus26** [comment]
hello Sebastian,
can you help me with `output: ` option?
here is what I want to do.
to create a switch or an option for `charger_source_priority` so I can select between all possible options.

I think will be something like this but dont know how to implement it
```
output:
  - platform: pipsolar
    pipsolar_id: inverter0
    charger_source_priority:
      possible_values: 
      - 0
      - 1
      - 2
      - 3
      id: inverter0_charger_source_priority_select 
```
I think that the command for charger source priority is PCP
so:
PCP00 - Utility first
PCP01- Solar first
PCP02- Solar and Utility
PCP03- Solar only

is there a way to make the a switch ( preferred method ) or to use it in automations.
thanks for looking
73 de KP4MI
best regards,
Miguel

**Comment by magnetus26** [comment]
hello
this is my solution:

substitutions:
  devicename: "SmartShunt"
  accuracy: "3"

  - platform: template
    name: " ${devicename} charge "
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: ${accuracy}
    lambda: |-
          float i = 264 + id(consumed_amp_hours).state;
          float e = id(bv).state;
          float w = 0.0;
          if (i > 0) {
            w =  i * e;
          }
          return {w};

  - platform: template
    name: " ${devicename} discharge "
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: ${accuracy}
    lambda: |-
          float i = id(consumed_amp_hours).state;
          float e = id(bv).state;
          float w = 0.0;
          if (i < 0) {
            w = i * e;
          }
          return {w * -1};

change the 264 for the amount of Ah of your batteries.
this will create 2 new sensors:
SmartShunt charge and SmartShunt discharge , use them in your Configure
battery system screen

[image: Capture]
<https://user-images.githubusercontent.com/22038983/196963624-da014030-2963-4626-bc24-4cc827e8d624.JPG>

**Reply by valeriotaccardo** [reply]
What pipsolar value is your " id(bv).state " and id(consumed_amp_hours).state ?

**Reply by magnetus26** [reply]
bv is batery voltage sensor
consumed_amp_hours is the sensor mamed that same way

**Comment by valeriotaccardo** [comment]
Hi! Is this correct?
Power Charging Battery: pv_input_current_for_battery * pv_input_voltage
Power Discharging Battery: battery_voltage * battery_discharge_current
Thank you?

**Reply by magnetus26** [reply]
no. 
Power Battery Charge is your battery Ah capacity + the consumed_amp_hours sensor multiplied by the bv sensor

Power Discharging Battery is:
just your comsumed^amp_hours sensor myltiply by bv that is your battery votlage sensor

if youbcopied the piece of code that I posted, you will have 2 new sensors, in this case they will be SmartShunt charge and SmartShunt discharge.
those sensors are the one that tou need to plug to your battery secrion in your energy dashboard 

![Screenshot_20221027-105850_Home Assistant](https://user-images.githubusercontent.com/22038983/198325361-c038fda1-a27b-49d3-8ef5-c18207c7eb74.jpg)

**Reply by valeriotaccardo** [reply]
Does you use pipsolar with esphome? I haven't sensor named consumed_amp_hours.
Can you post all your yaml please?

**Comment by magnetus26** [comment]
no  I use victron smartshunt, by KinDR007 for my battery sensors. I just use pipsolar to monitor my mppsolar inverter.

here is my code:
```
esphome:
  name: "${lower_devicename}"
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://KinDR007/VictronSmartShunt-ESPHOME@main
    refresh: 0s

substitutions:
  lower_devicename: "smartshunt"
  devicename: "SmartShunt"
  config_version: "v2021.06.02.001"
  wifi_fast_connect: "true"
  accuracy: "3"

wifi:
  ssid: "!secret"
  password: "!secret"
  fast_connect: true
  power_save_mode: none
  
  manual_ip:
    static_ip: 10.0.0.27
    gateway: 10.0.0.138
    subnet: 255.255.255.0
    dns1: 10.0.0.138

  ap:
    ssid: "${devicename} Hotspot"
    password: "12345678"

captive_portal:

logger:

api:

ota:

web_server:
  port: 80

time:
  - platform: homeassistant

uart:
  id: uart0
  tx_pin: D8
  rx_pin: D7
  baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

victron_smart_shunt:
  uart_id: uart0

sensor:
  - platform: victron_smart_shunt
    battery_voltage:
      name: "Battery Voltage"
      id: bv
      accuracy_decimals: ${accuracy}

    battery_current:
      name: "Battery Current"
      id: bc 
      accuracy_decimals: ${accuracy}

    instanteneous_power:
      name: "instanteneous power"
      id: instantaneous_power 
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
      accuracy_decimals: ${accuracy}

    time_to_go:
      name: "time to go"
      id: time_to_go

    consumed_amp_hours:
      name: "consumed amp hours"
      id: consumed_amp_hours
      unit_of_measurement: Ah
      accuracy_decimals: ${accuracy}

    min_battery_voltage:
      name: "Min battery voltage"
      id: min_battery_voltage
      accuracy_decimals: ${accuracy}

    max_battery_voltage:
      name: "Max battery voltage"
      id: max_battery_voltage
      accuracy_decimals: ${accuracy}

    amount_of_charged:
      name: "Amount of charged"
      id:  amount_of_charged   
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: ${accuracy}
      
    bmv_alarm_text:
      name: "BMV alarm"
      id: bmv_alarm

    
    last_full_charge:
      name: "Time since last full charge"
      id: last_full_charge

    deepest_discharge:
      name: "Depth of the deepest discharge"
      id: deepest_discharge
      unit_of_measurement: Ah
      accuracy_decimals: ${accuracy}

    last_discharge:
      name: "Depth of the last discharge"
      id: last_discharge
      unit_of_measurement: Ah
      accuracy_decimals: ${accuracy}

    state_of_charge:
      id: state_of_charge
      name: "SoC"

    discharged_energy:
      name: "Amount of discharged energy"
      id: discharged_energy   
      filters:
        - multiply: 0.001
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: ${accuracy}
      
  - platform: template
    name: " ${devicename} discharge "
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: ${accuracy}
    lambda: |-
          float i = id(consumed_amp_hours).state;
          float e = id(bv).state;
          float w = 0.0;
          if (i < 0) {
            w = i * e;
          }
          return {w * -1};
     
    
  - platform: template
    name: " ${devicename} charge "
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: ${accuracy}
    lambda: |-
          float i = 264 + id(consumed_amp_hours).state; 
          float e = id(bv).state;
          float w = 0.0;
          if (i > 0) {
            w =  i * e;
          }
          return {w};
      

switch:
  - platform: restart
    icon: mdi:reload-alert
    name: "${devicename} Restart"
```
in the 
```
 - platform: template
    name: " ${devicename} charge "
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: ${accuracy}
    lambda: |-
          float i = 264 + id(consumed_amp_hours).state; 
          float e = id(bv).state;
          float w = 0.0;
          if (i > 0) {
            w =  i * e;
          }
          return {w}; "
```

1-  you will need to replace the number 264 in the following line: ` float i = 264 + id(consumed_amp_hours).state; ` for the number of Ah 
     of your battery bank.

2- look at the 2 ` - platform: template` devices, those are the ones that you have to plug to your energy dashboard.

![Capture](https://user-images.githubusercontent.com/22038983/198722155-9f5641ee-3281-41c5-9f59-f0c21ada8d99.JPG)

3- I also removed everything related with Wi-Fi monitoring in my code.

4- one last thing in the `wifi` section I added a static ip, you can remove the following lines to keep it DHCP so for router will assign an IP 
    to your esp device.
```
manual_ip:
    static_ip: 10.0.0.27
    gateway: 10.0.0.138
    subnet: 255.255.255.0
    dns1: 10.0.0.138
```
I hope this helps, just let us know.
best regards,
Miguel
