### DISCUSSION TITLE
How to change max charging values?

### DISCUSSION THREAD

**Discussion by carmelo42** [syssi/esphome-pipsolar#163] [Q&A]
Hi ! 
How can I change the max AC charging value ? 
I tried this : 

```
output:
  - platform: pipsolar
    pipsolar_id: inverter0
    battery_recharge_voltage:
      id: inverter0_battery_recharge_voltage_out
    current_max_ac_charging_current:
      id: inverter0_current_max_ac_charging_current
      possible_values: [10,20,30,40]
    current_max_charging_current:
      id: inverter0_current_max_charging_current
      possible_values: [10,20,30,40]

```

But I can't see how to change the values from Home Assistant.

Thanks ;)
