### ISSUE TITLE
Too many measurment sent to Home Assistant

### ISSUE THREAD

**Issue by charger** [syssi/esphome-pipsolar#145]
My device sent measurments to HomeAssistant via API each moment. I would say it is two times per second. And HA logs too many points and because of the amount of point it is hard to show a historical graph.
 Is there a way to lower the reporting rate in ESPHome? Or logs only changed values in HA?

My config: 
```yml
esphome:
  name: hybridinvertor
  min_version: 2024.6.0

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "U6m..."

ota:
  - platform: esphome
    password: "c1..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

status_led:
  pin: GPIO2

captive_portal:
    

substitutions:
  name: hybridinvertor
  tx_pin: GPIO4
  rx_pin: GPIO5

uart:
  id: uart_0
  baud_rate: 2400
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

pipsolar:
  uart_id: uart_0
  id: inverter0

sensor:
  - platform: pipsolar
    pipsolar_id: inverter0


    # QPIGS
    grid_voltage:
      name: "grid_voltage"
    grid_frequency:
      name: "grid_frequency"
    ac_output_voltage:
      name: "ac_output_voltage"
    ac_output_active_power:
      name: "ac_output_active_power"
    output_load_percent:
      name: "output_load_percent"
    bus_voltage:
      name: "bus_voltage"
    battery_voltage:
      name: "battery_voltage"
    battery_charging_current:
      name: "battery_charging_current"
    battery_capacity_percent:
      name: "battery_capacity_percent"
    inverter_heat_sink_temperature:
      name: "inverter_heat_sink_temperature"
    pv_input_current_for_battery:
      name: "pv_input_current_for_battery"
    pv_input_voltage:
      name: "pv_input_voltage"
    battery_voltage_scc:
      name: "battery_voltage_scc"
    battery_discharge_current:
      name: "battery_discharge_current"
    pv_charging_power:
      name: "pv_charging_power"

text_sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    device_mode:
      name: "device_mode"

binary_sensor:
  #Main Power Supply on/off
  - platform: gpio
    pin: 
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: power_grid_availability
    device_class: power

  #invertor part
  - platform: pipsolar
    pipsolar_id: inverter0
    add_sbu_priority_version:
      name: "add_sbu_priority_version"
    configuration_status:
      name: "configuration_status"

    load_status:
      name: "load_status"
    charging_status:
      name: "charging_status"

switch:
  - platform: pipsolar
    pipsolar_id: inverter0
    output_source_priority_utility:
      name: "output_source_priority_utility"
    output_source_priority_solar:
      name: "output_source_priority_solar"
    output_source_priority_battery:
      name: "output_source_priority_battery"
```

Thank for the library!

**Comment by syssi** [comment]
Please increate the `update_interval` from `1s` (default) to f.e. 60s:

```
pipsolar:
  uart_id: uart_0
  id: inverter0
  update_interval: 60s
```
