### ISSUE TITLE
battery_discharge_current showing zero

### ISSUE THREAD

**Issue by reflexsa** [syssi/esphome-pipsolar#50]
Hi all,

I have been using pipsolar with a ESP32-cam for a while and it has been running well. My inverter is an Axpert VMII 1.2kW.
When I initially setup pipsolar I noticed that one missing sensor is my battery_discharge_current.
This always shows 0. I noticed that in the last_qpigs message it reads correctly there.
At the moment I am extracting the value using a sensor in my configuration.yaml. See below code:

```
#extract battery discharge current from qpigs message
  - sensor:
      - name: "inverter0_battery_discharge_qpigs"
        unit_of_measurement: "A"
        availability: >
          {{states('sensor.inverter0_last_qpigs')[78:82] not in ['unavailable', 'unknown']}}
        state: >
          {{states('sensor.inverter0_last_qpigs')[78:82] | float(0)}}
```

Doing it this way causes a lot of unwanted data to be transferred and also stored in my history.
Is there a way to only send the battery discharge current section of the qpigs (basically use this code on the ESP) or to get the original "battery_discharge_current" sensor working?

Thank you for any help and advice.

**Comment by reflexsa** [comment]
Managed to solve this using a lambda filter. Perhaps there is a way to use the other text sensor filters and more efficient ways but this seemed to work.
On the ESP:
```
text_sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    last_qpigs:
      id: inverter0_last_qpigs
      name: inverter0_battery_discharge_current_qpigs
      filters:
        - lambda: |-
            return x.substr(78,4);
```

In the configuration.yaml:
```
#convert battery discharge current from to float
  - sensor:
      - name: "inverter0_battery_discharge_qpigs"
        unit_of_measurement: "A"
        availability: >
          {{states('sensor.inverter0_battery_discharge_current_qpigs') not in ['unavailable', 'unknown']}}
        state: >
          {{states('sensor.inverter0_battery_discharge_current_qpigs') | float(0)}}
```
