### ISSUE TITLE
Easun smh 3k

### ISSUE THREAD

**Issue by Warloo93** [syssi/esphome-pipsolar#59]
Hello. 
I am trying to configure my inverter to HA without luck. 
I think hardware wiring is good, here is picture : 
![IMG20230309001012](https://user-images.githubusercontent.com/116860821/224005322-d5061ffe-dc3f-4a2b-be26-0db4c4c6039f.jpg)
One from the inverter : 
![IMG20230309115445](https://user-images.githubusercontent.com/116860821/224005369-624ebc18-de69-44af-9581-36d2d4a50f1c.jpg)

And here is the debug from watchpower and log from esphome in zip. [Zip](https://drive.google.com/file/d/17_66NXF-hrRubD033psy2vlOuQ0S4Gh9/view?usp=drivesdk) 

I tried to add diferent external components but no one worked. 

Here is my current config : 

```
esphome:
  name: solar
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    uart: VERY_VERBOSE
    uart.arduino_esp8266: VERY_VERBOSE
    
# Enable Home Assistant API
api:

ota:
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Solar Fallback Hotspot"

captive_portal:

uart:
  - id: uart_bus
    tx_pin: TX
    rx_pin: RX
    # most devices use 2400 as baud_rate
    baud_rate: 2400

pipsolar:
  - uart_id: uart_bus
    id: inverter0

sensor:
  - platform: pipsolar
    pipsolar_id: inverter0

    grid_rating_current:
      id: inverter0_grid_rating_current
      name: inverter0_grid_rating_current
    ac_output_active_power:
      id: inverter0_ac_output_active_power
      name: inverter0_ac_output_active_power
    ac_output_apparent_power:
      id: inverter0_ac_output_apparent_power
      name: inverter0_ac_output_apparent_power
    ac_output_voltage:
      id: inverter0_ac_output_voltage
      name: inverter0_ac_output_voltage
    battery_capacity_percent:
      id: inverter0_battery_capacity_percent
      name: inverter0_battery_capacity_percent
    battery_charging_current:
      id: inverter0_battery_charging_current
      name: inverter0_battery_charging_current
    battery_discharge_current:
      id: inverter0_battery_discharge_current
      name: inverter0_battery_discharge_current
    battery_voltage:
      id: inverter0_battery_voltage
      name: inverter0_battery_voltage
    grid_voltage:
      id: inverter0_grid_voltage
      name: inverter0_grid_voltage
    inverter_heat_sink_temperature:
      id: inverter0_inverter_heat_sink_temperature
      name: inverter0_inverter_heat_sink_temperature
    output_load_percent:
      id: inverter0_output_load_percent
      name: inverter0_output_load_percent
    pv_charging_power:
      id: inverter0_pv_charging_power
      name: inverter0_pv_charging_power
    pv_input_voltage:
      id: inverter0_pv_input_voltage
      name: inverter0_pv_input_voltage
    

    
text_sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    device_mode:
      id: inverter0_device_mode
      name: inverter0_device_mode
    last_qpigs:
      id: inverter0_last_qpigs
      name: inverter0_last_qpigs
    last_qpiri:
      id: inverter0_last_qpiri
      name: inverter0_last_qpiri
      
switch:
  - platform: pipsolar
    pipsolar_id: inverter0
    output_source_priority_utility:
      name: inverter0_output_source_priority_utility
    output_source_priority_solar:
      name: inverter0_output_source_priority_solar
    output_source_priority_battery:
      name: inverter0_output_source_priority_battery
    input_voltage_range:
      name: inverter0_input_voltage_range
    pv_power_balance:
      name: inverter0_pv_power_balance
```

Thank you for the support.

**Comment by Warloo93** [comment]
And i cannot find where need to write this code : 

# Install esphome
pip3 install esphome

# Clone this external component
git clone https://github.com/syssi/esphome-pipsolar.git
cd esphome-pipsolar

# Create a secret.yaml containing some setup specific secrets
cat > secrets.yaml <<EOF
mqtt_host: MY_MQTT_HOST
mqtt_username: MY_MQTT_USERNAME
mqtt_password: MY_MQTT_PASSWORD

wifi_ssid: MY_WIFI_SSID
wifi_password: MY_WIFI_PASSWORD
EOF

# Validate the configuration, create a binary, upload it, and start logs
# If you use a esp8266 run the esp8266-examle.yaml
esphome run esp32-example.yaml

i tried into esp config, HA terminal but nothing works

**Comment by syssi** [comment]
If you use RX/TX (GPIO1/GPIO3) instead of GPIO4/5 you have to set the `baud_rate` of the `logger` to `0`:

```
logger:
  baud_rate: 0
  level: VERY_VERBOSE
  logs:
    uart: VERY_VERBOSE
    uart.arduino_esp8266: VERY_VERBOSE
```

The logger is attached to GPIO1/GPIO3 per default.

**Comment by syssi** [comment]
Please flash this YAML as first step:

https://raw.githubusercontent.com/syssi/esphome-pipsolar/main/tests/esp8266-test-protocols.yaml

Please attach the inverter/rs232 module to GPIO4/GPIO5 and provide the log output. It should show some outgoing and incoming traffic. So we get an idea which protocol version your inverter supports.

**Comment by Warloo93** [comment]
Thank you for response.
My bad, i connected the rs232 revesed, and ttl side too. 
Now is working, only problem i have with temperature meter, its showing 400-700 °C.

**Comment by syssi** [comment]
Do you know the command (QPIGS, QPIRI?) which returns the temperature? Could you provide an example response containing the temperature?

**Comment by Warloo93** [comment]
Do you mean this log ? 

`[12:44:14][D][pipsolar:836]: Sending polling command : QPIGS with length 5
[12:44:14][D][pipsolar:772]: checking crc on incoming message
[12:44:14][D][pipsolar:775]: CRC OK
[12:44:14][D][pipsolar:448]: Decode QPIGS
[12:44:14][D][sensor:126]: 'easun grid_voltage': Sending state 241.00000 V with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun grid_frequency': Sending state 50.00000 Hz with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun ac_output_voltage': Sending state 228.00000 V with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun ac_output_frequency': Sending state 50.10000 Hz with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun ac_output_apparent_power': Sending state 0.00000 VA with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun ac_output_active_power': Sending state 0.00000 W with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun output_load_percent': Sending state 0.00000 % with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun bus_voltage': Sending state 419.00000 V with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun battery_voltage': Sending state 28.26000 V with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun battery_charging_current': Sending state 12.00000 A with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun battery_capacity_percent': Sending state 100.00000 % with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun inverter_heat_sink_temperature': Sending state 696.00000 °C with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun pv_input_current_for_battery': Sending state 13.00000 A with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun pv_input_voltage': Sending state 73.10000 V with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun battery_voltage_scc': Sending state 28.11000 V with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun battery_discharge_current': Sending state 0.00000 A with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun battery_voltage_offset_for_fans_on': Sending state 0.00000 V with 1 decimals of accuracy
[12:44:14][D][sensor:126]: 'easun pv_charging_power': Sending state 389.00000 W with 1 decimals of accuracy`

**Comment by syssi** [comment]
Not exactly. I'm looking for the value of the `text_sensor.last_qpigs` sensor.

**Comment by Warloo93** [comment]
I dont see .last_qpigs in my log 
[14:14:09][C][wifi:504]: WiFi:
[14:14:09][C][wifi:362]:   Local MAC: A0:20:A6:02:56:4C
[14:14:09][C][wifi:363]:   SSID: [redacted]
[14:14:09][C][wifi:364]:   IP Address: 192.168.1.15
[14:14:09][C][wifi:365]:   BSSID: [redacted]
[14:14:09][C][wifi:367]:   Hostname: 'easun'
[14:14:09][C][wifi:369]:   Signal strength: -90 dB ▂▄▆█
[14:14:09][C][wifi:373]:   Channel: 13
[14:14:09][C][wifi:374]:   Subnet: 255.255.255.0
[14:14:09][C][wifi:375]:   Gateway: 192.168.1.1
[14:14:09][C][wifi:376]:   DNS1: 0.0.0.0
[14:14:09][C][wifi:377]:   DNS2: 0.0.0.0
[14:14:09][C][logger:293]: Logger:
[14:14:09][C][logger:294]:   Level: DEBUG
[14:14:09][C][logger:295]:   Log Baud Rate: 0
[14:14:09][C][logger:296]:   Hardware UART: UART0
[14:14:09][C][uart.arduino_esp8266:102]: UART Bus:
[14:14:09][C][uart.arduino_esp8266:103]:   TX Pin: GPIO3
[14:14:09][C][uart.arduino_esp8266:104]:   RX Pin: GPIO1
[14:14:09][C][uart.arduino_esp8266:106]:   RX Buffer Size: 256
[14:14:09][C][uart.arduino_esp8266:108]:   Baud Rate: 2400 baud
[14:14:09][C][uart.arduino_esp8266:109]:   Data Bits: 8
[14:14:09][C][uart.arduino_esp8266:110]:   Parity: NONE
[14:14:09][C][uart.arduino_esp8266:111]:   Stop bits: 1
[14:14:09][C][uart.arduino_esp8266:115]:   Using software serial
[14:14:09][C][pipsolar:860]: Pipsolar:
[14:14:09][C][pipsolar:861]: used commands:
[14:14:09][C][pipsolar:864]: QPIGS
[14:14:09][C][pipsolar:864]: QMOD
[14:14:09][C][pipsolar:864]: QFLAG
[14:14:09][C][pipsolar:864]: QPIRI
[14:14:09][C][pipsolar.switch:076]: Pipsolar Switch 'easun output_source_priority_utility'
[14:14:09][C][pipsolar.switch:078]:   Icon: 'mdi:power'
[14:14:09][C][pipsolar.switch:098]:   Restore Mode: restore defaults to OFF
[14:14:09][C][pipsolar.switch:076]: Pipsolar Switch 'easun output_source_priority_solar'
[14:14:09][C][pipsolar.switch:078]:   Icon: 'mdi:power'
[14:14:09][C][pipsolar.switch:098]:   Restore Mode: restore defaults to OFF
[14:14:09][C][pipsolar.switch:076]: Pipsolar Switch 'easun output_source_priority_battery'
[14:14:09][C][pipsolar.switch:078]:   Icon: 'mdi:power'
[14:14:09][C][pipsolar.switch:098]:   Restore Mode: restore defaults to OFF
[14:14:09][C][pipsolar.switch:076]: Pipsolar Switch 'easun input_voltage_range'
[14:14:09][C][pipsolar.switch:078]:   Icon: 'mdi:power'
[14:14:09][C][pipsolar.switch:098]:   Restore Mode: restore defaults to OFF
[14:14:09][C][pipsolar.switch:076]: Pipsolar Switch 'easun pv_ok_condition_for_parallel'
[14:14:09][C][pipsolar.switch:078]:   Icon: 'mdi:power'
[14:14:09][C][pipsolar.switch:098]:   Restore Mode: restore defaults to OFF
[14:14:09][C][pipsolar.switch:076]: Pipsolar Switch 'easun pv_power_balance'
[14:14:09][C][pipsolar.switch:078]:   Icon: 'mdi:power'
[14:14:09][C][pipsolar.switch:098]:   Restore Mode: restore defaults to OFF
[14:14:10][C][mdns:108]: mDNS:
[14:14:10][C][mdns:109]:   Hostname: easun
[14:14:10][C][ota:093]: Over-The-Air Updates:
[14:14:10][C][ota:094]:   Address: 192.168.1.15:8266
[14:14:10][C][api:138]: API Server:
[14:14:10][C][api:139]:   Address: 192.168.1.15:6053
[14:14:10][C][api:143]:   Using noise encryption: NO
[14:14:10][D][pipsolar:836]: Sending polling command : QMOD with length 4
[14:14:10][D][pipsolar:772]: checking crc on incoming message
[14:14:10][D][pipsolar:775]: CRC OK
[14:14:10][D][pipsolar:471]: Decode QMOD
[14:14:10][D][text_sensor:067]: 'easun device_mode': Sending state 'B'
[14:14:10][D][pipsolar:836]: Sending polling command : QFLAG with length 5
[14:14:10][D][pipsolar:772]: checking crc on incoming message
[14:14:10][D][pipsolar:775]: CRC OK
[14:14:10][D][pipsolar:479]: Decode QFLAG
[14:14:11][D][pipsolar:836]: Sending polling command : QPIRI with length 5
[14:14:12][D][pipsolar:772]: checking crc on incoming message
[14:14:12][D][pipsolar:775]: CRC OK
[14:14:12][D][pipsolar:429]: Decode QPIRI
[14:14:12][D][pipsolar:836]: Sending polling command : QPIGS with length 5
[14:14:13][D][pipsolar:772]: checking crc on incoming message
[14:14:13][D][pipsolar:775]: CRC OK
[14:14:13][D][pipsolar:448]: Decode QPIGS

**Comment by syssi** [comment]
Did you remove this sensor from your YAML?

```
text_sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    last_qpigs:
      id: inverter0_last_qpigs
      name: inverter0_last_qpigs
```
